import { StyleSheet, Platform } from 'react-native';
import { colors, spacing, fontSize, fontWeight, radius, shadows } from '@theme/index';

export const loginStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.primaryDark },
  splitContainer: { flex: 1, flexDirection: 'row' },
  // Brand Panel
  brandPanel: { flex: 0.42, position: 'relative', backgroundColor: colors.primaryDark, overflow: 'hidden' },
  brandBgImage: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, width: '100%', height: '100%' },
  brandOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(6, 40, 61, 0.82)' },
  brandContent: { flex: 1, padding: spacing.xxl, justifyContent: 'space-between' },
  brandLogoSection: { alignItems: 'flex-start' },
  logoRing: { width: 56, height: 56, borderRadius: 28, borderWidth: 2, borderColor: colors.accent, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  logoInner: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center' },
  logoText: { fontSize: fontSize.xs, fontWeight: fontWeight.extrabold, color: colors.primaryDark, letterSpacing: 1 },
  brandTitle: { fontSize: fontSize.xl, fontWeight: fontWeight.bold, color: colors.white, lineHeight: fontSize.xl * 1.3, marginBottom: spacing.xs },
  brandTagline: { fontSize: fontSize.sm, color: colors.accent, fontWeight: fontWeight.medium, letterSpacing: 0.5 },
  // Carousel
  carouselContainer: { flex: 1, justifyContent: 'center', marginVertical: spacing.xl },
  carouselSlide: { borderRadius: radius.lg, overflow: 'hidden', position: 'relative', ...shadows.lg, minHeight: 240 },
  carouselImage: { width: '100%', height: '100%', position: 'absolute', top: 0, left: 0 },
  carouselImageOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(6, 40, 61, 0.65)' },
  carouselTextWrap: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: spacing.lg },
  carouselAccentBar: { width: 32, height: 3, borderRadius: 2, marginBottom: spacing.sm },
  carouselTitle: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.white, marginBottom: 4, letterSpacing: 0.3 },
  carouselText: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.75)', lineHeight: fontSize.xs * 1.6 },
  carouselDots: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.md, gap: 6 },
  carouselDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255, 255, 255, 0.2)' },
  carouselDotActive: { width: 20, borderRadius: 4 },
  // Stats
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: spacing.lg, borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.1)' },
  statItem: { alignItems: 'center' },
  statValue: { fontSize: fontSize.lg, fontWeight: fontWeight.extrabold, color: colors.white },
  statLabel: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.5)', marginTop: 2, letterSpacing: 0.3 },
  // Compact Header
  compactHeader: { backgroundColor: colors.primaryDark, paddingVertical: spacing.md, paddingHorizontal: spacing.lg, borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.08)' },
  compactLogoRow: { flexDirection: 'row', alignItems: 'center' },
  compactLogoRing: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center', marginRight: spacing.md },
  compactLogoText: { fontSize: fontSize.xs, fontWeight: fontWeight.extrabold, color: colors.primaryDark },
  compactTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.white },
  compactSubtitle: { fontSize: fontSize.xs, color: colors.accent },
  // Form Panel
  formPanel: { flex: 0.5, backgroundColor: colors.primaryDark, justifyContent: 'center', position: 'relative' },
  formPanelBg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, width: '100%', height: '100%' },
  formPanelBgOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(6, 40, 61, 0.75)' },
  formPanelInner: {
    flex: 1,
    maxWidth: 400,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    marginHorizontal: spacing.lg,
    marginVertical: spacing.lg,
    overflow: 'hidden',
    ...(Platform.OS === 'web' ? { backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)' } as any : {}),
  },
  formHeader: { marginBottom: spacing.md },
  formWelcome: { fontSize: fontSize.xl, fontWeight: fontWeight.extrabold, color: colors.white, marginBottom: 2 },
  formWelcomeSub: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)' },
  // Tab Bar
  tabBar: { flexDirection: 'row', borderBottomWidth: 1.5, borderBottomColor: 'rgba(255, 255, 255, 0.1)', marginBottom: spacing.md },
  tabItem: { flex: 1, paddingVertical: spacing.sm + 2, alignItems: 'center', position: 'relative' },
  tabLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: 'rgba(255, 255, 255, 0.4)', letterSpacing: 0.3 },
  tabLabelActive: { color: colors.accent, fontWeight: fontWeight.bold },
  tabIndicator: { position: 'absolute', bottom: -2, left: '20%', right: '20%', height: 3, borderRadius: 2, backgroundColor: colors.accent },
  // Form Content
  formContent: { flex: 1 },
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: spacing.lg },
  // Fields
  fieldGroup: { marginBottom: spacing.sm + 2 },
  fieldLabel: { fontSize: fontSize.xs, fontWeight: fontWeight.semibold, color: 'rgba(255, 255, 255, 0.55)', marginBottom: 2, letterSpacing: 0.3 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: 'rgba(255, 255, 255, 0.12)', borderRadius: radius.md, backgroundColor: 'rgba(255, 255, 255, 0.06)', paddingHorizontal: spacing.md },
  inputIcon: { fontSize: fontSize.sm, marginRight: spacing.sm, opacity: 0.4 },
  textInput: { flex: 1, paddingVertical: spacing.sm + 2, fontSize: fontSize.sm, color: colors.white },
  passwordToggle: { padding: spacing.xs },
  passwordToggleText: { fontSize: fontSize.md },
  // Buttons
  primaryButton: { backgroundColor: colors.accent, borderRadius: radius.md, paddingVertical: spacing.sm + 4, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.sm, marginTop: spacing.md },
  primaryButtonSmall: { backgroundColor: colors.accent, borderRadius: radius.md, paddingVertical: spacing.sm + 4, paddingHorizontal: spacing.lg, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: spacing.sm },
  primaryButtonDisabled: { opacity: 0.5 },
  primaryButtonText: { color: colors.primaryDark, fontSize: fontSize.sm, fontWeight: fontWeight.bold, letterSpacing: 0.5 },
  primaryButtonArrow: { color: colors.primaryDark, fontSize: fontSize.md, fontWeight: fontWeight.bold },
  secondaryButton: { borderRadius: radius.md, paddingVertical: spacing.sm + 2, alignItems: 'center', marginTop: spacing.xs, borderWidth: 1.5, borderColor: 'rgba(255, 255, 255, 0.15)', backgroundColor: 'transparent' },
  secondaryButtonText: { color: 'rgba(255, 255, 255, 0.7)', fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
  forgotRow: { flexDirection: 'row', justifyContent: 'flex-end', marginBottom: spacing.xs, marginTop: spacing.xs },
  forgotText: { color: colors.accent, fontSize: fontSize.xs, fontWeight: fontWeight.medium },
  // Divider
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginVertical: spacing.md },
  dividerLine: { flex: 1, height: 1, backgroundColor: 'rgba(255, 255, 255, 0.1)' },
  dividerText: { fontSize: 9, color: 'rgba(255, 255, 255, 0.35)', fontWeight: fontWeight.medium, paddingHorizontal: spacing.sm, letterSpacing: 1 },
  // Trust
  trustRow: { flexDirection: 'row', justifyContent: 'space-around' },
  trustItem: { alignItems: 'center' },
  trustIcon: { fontSize: fontSize.md, marginBottom: 2 },
  trustText: { fontSize: 10, color: 'rgba(255, 255, 255, 0.4)', fontWeight: fontWeight.medium },
  // Error
  errorBox: { backgroundColor: 'rgba(229, 72, 77, 0.15)', borderRadius: radius.md, padding: spacing.sm + 2, marginBottom: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: 'rgba(229, 72, 77, 0.3)' },
  errorIconWrap: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.danger, justifyContent: 'center', alignItems: 'center' },
  errorIcon: { color: colors.white, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  errorText: { color: colors.danger, fontSize: fontSize.sm, flex: 1, fontWeight: fontWeight.medium },
  errorDismissBtn: { padding: spacing.xs },
  errorDismiss: { color: colors.danger, fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  // Step Indicator
  stepIndicatorRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md, paddingHorizontal: spacing.xs },
  stepIndicatorItem: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  stepCircle: { width: 24, height: 24, borderRadius: 12, backgroundColor: 'rgba(255, 255, 255, 0.08)', borderWidth: 2, borderColor: 'rgba(255, 255, 255, 0.15)', justifyContent: 'center', alignItems: 'center', marginRight: spacing.xs },
  stepCircleComplete: { backgroundColor: colors.success, borderColor: colors.success },
  stepCircleCurrent: { borderColor: colors.accent, backgroundColor: colors.accent },
  stepCircleText: { fontSize: fontSize.xs, fontWeight: fontWeight.bold, color: 'rgba(255, 255, 255, 0.4)' },
  stepCircleTextActive: { color: colors.primaryDark },
  stepLabel: { fontSize: fontSize.xs, fontWeight: fontWeight.medium, color: 'rgba(255, 255, 255, 0.4)' },
  stepLabelActive: { color: colors.white, fontWeight: fontWeight.semibold },
  stepConnector: { flex: 1, height: 2, backgroundColor: 'rgba(255, 255, 255, 0.1)', marginHorizontal: spacing.xs },
  stepConnectorComplete: { backgroundColor: colors.success },
  // Section
  formSectionTitle: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.white, marginBottom: 2 },
  formSectionSub: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.55)', marginBottom: spacing.sm },
  // Alerts
  alertBoxSuccess: { backgroundColor: 'rgba(11, 163, 122, 0.15)', borderRadius: radius.md, padding: spacing.sm + 2, marginBottom: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: 'rgba(11, 163, 122, 0.3)' },
  alertIconWrapSuccess: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.success, justifyContent: 'center', alignItems: 'center' },
  alertTextSuccess: { fontSize: fontSize.sm, color: colors.success, fontWeight: fontWeight.medium, flex: 1 },
  alertBoxWarning: { backgroundColor: 'rgba(245, 158, 11, 0.15)', borderRadius: radius.md, padding: spacing.sm + 2, marginBottom: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderWidth: 1, borderColor: 'rgba(245, 158, 11, 0.3)' },
  alertIconWrapWarning: { width: 24, height: 24, borderRadius: 12, backgroundColor: colors.warning, justifyContent: 'center', alignItems: 'center' },
  alertTextWarning: { fontSize: fontSize.sm, color: colors.warning, fontWeight: fontWeight.medium, flex: 1 },
  alertIcon: { color: colors.white, fontSize: fontSize.xs, fontWeight: fontWeight.bold },
  // Payment
  paymentMethodRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  paymentMethodCard: { flex: 1, backgroundColor: 'rgba(255, 255, 255, 0.06)', borderRadius: radius.md, paddingVertical: spacing.sm + 2, paddingHorizontal: spacing.xs, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  paymentMethodActive: { borderColor: colors.accent, backgroundColor: 'rgba(255, 201, 60, 0.12)' },
  paymentMethodIcon: { fontSize: fontSize.md, marginBottom: 2 },
  paymentMethodLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: 'rgba(255, 255, 255, 0.85)' },
  // Step Nav
  stepNavRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.md, gap: spacing.sm },
  backBtn: { paddingVertical: spacing.sm, paddingHorizontal: spacing.md },
  backBtnText: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', fontWeight: fontWeight.medium },
  // Privacy
  privacyNotice: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.45)', marginVertical: spacing.sm, lineHeight: 16 },
  hintText: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.35)', fontStyle: 'italic', marginTop: spacing.xs },
  // Success
  successContainer: { alignItems: 'center', paddingVertical: spacing.xl },
  successIconWrap: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.success, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  successIcon: { fontSize: fontSize.xxl, color: colors.white, fontWeight: fontWeight.bold },
  successTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.success, textAlign: 'center', marginBottom: spacing.xs },
  successSubtext: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', lineHeight: fontSize.sm * 1.5, marginBottom: spacing.xs },
  successSubtext2: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', lineHeight: fontSize.sm * 1.5, marginBottom: spacing.lg },
  // Result boxes
  resultBoxDanger: { backgroundColor: 'rgba(229, 72, 77, 0.12)', borderRadius: radius.lg, padding: spacing.lg, alignItems: 'center' },
  resultIconWrapDanger: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.danger, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  resultIcon: { fontSize: fontSize.xl, color: colors.white, fontWeight: fontWeight.bold },
  resultTitleDanger: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.danger, marginBottom: spacing.sm },
  resultTextDanger: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', lineHeight: fontSize.sm * 1.5 },
  resultBoxSuccess: { backgroundColor: 'rgba(11, 163, 122, 0.12)', borderRadius: radius.lg, padding: spacing.lg, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(11, 163, 122, 0.25)' },
  resultIconWrapSuccess: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.success, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  resultTitleSuccess: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.success, marginBottom: spacing.sm },
  resultTextSuccess: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', marginBottom: spacing.sm },
  resultDetailText: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.85)', marginTop: spacing.xs },
  resultBoxWarning: { backgroundColor: 'rgba(245, 158, 11, 0.12)', borderRadius: radius.lg, padding: spacing.lg, alignItems: 'center' },
  resultIconWrapWarning: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.warning, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  resultTitleWarning: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.warning, marginBottom: spacing.sm },
  resultTextWarning: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', marginTop: spacing.xs },
  resultSubtext: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', textAlign: 'center', lineHeight: fontSize.sm * 1.5, marginTop: spacing.sm },
  feeWarning: { fontSize: fontSize.sm, color: colors.danger, fontWeight: fontWeight.semibold, marginTop: spacing.sm },
  // Credentials
  credentialsBox: { backgroundColor: 'rgba(59, 130, 246, 0.12)', borderRadius: radius.md, padding: spacing.md, marginTop: spacing.md },
  credentialsTitle: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.info, marginBottom: spacing.xs },
  credentialsDetail: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.85)', marginTop: spacing.xs },
  credentialsHint: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.4)', fontStyle: 'italic', marginTop: spacing.sm },
  // Prospectus
  prospectusCard: { backgroundColor: 'rgba(255, 255, 255, 0.06)', borderRadius: radius.md, padding: spacing.md, marginTop: spacing.sm, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.1)' },
  prospectusTitle: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.white },
  prospectusMeta: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.5)', marginTop: 2 },
  prospectusPreview: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', marginTop: spacing.xs, lineHeight: fontSize.sm * 1.4 },
  downloadBtn: { backgroundColor: colors.accent, borderRadius: radius.md, paddingVertical: spacing.sm, paddingHorizontal: spacing.md, marginTop: spacing.sm, alignSelf: 'flex-start' },
  downloadBtnText: { color: colors.primaryDark, fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
  // Footer
  footerBar: { paddingVertical: spacing.sm, alignItems: 'center', borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.08)' },
  footerText: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.35)', letterSpacing: 0.5 },
  // ── HOME PAGE (Bright & Vibrant) ──
  homeScreen: { flex: 1, backgroundColor: '#f0f4ff' },
  homeScroll: { flex: 1 },
  homeScrollContent: { flexGrow: 1 },
  // Header
  header: {
    position: 'absolute', top: 0, left: 0, right: 0, zIndex: 100,
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingHorizontal: spacing.xl + 8, paddingVertical: spacing.md,
    ...(Platform.OS === 'web' ? { backdropFilter: 'blur(20px)', WebkitBackdropFilter: 'blur(20px)' } as any : {}),
    backgroundColor: 'rgba(255, 255, 255, 0.85)', borderBottomWidth: 1, borderBottomColor: 'rgba(15, 76, 117, 0.08)',
  },
  headerLogoRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm + 2 },
  headerLogoBox: { width: 44, height: 44, borderRadius: 12, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', ...shadows.sm },
  headerLogoText: { fontSize: fontSize.xs, fontWeight: fontWeight.extrabold, color: colors.white, letterSpacing: 1.5 },
  headerSchoolName: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.primary, letterSpacing: 0.3 },
  headerSchoolSub: { fontSize: 10, color: colors.textSecondary, fontWeight: fontWeight.medium, letterSpacing: 0.5 },
  headerNav: { flexDirection: 'row', alignItems: 'center', gap: spacing.xl },
  headerNavLink: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: colors.textSecondary, letterSpacing: 0.3 },
  headerNavLinkActive: { color: colors.primary },
  headerCtaBtn: { backgroundColor: colors.primary, borderRadius: radius.md, paddingVertical: spacing.sm + 2, paddingHorizontal: spacing.lg + 4, ...shadows.sm },
  headerCtaText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.white, letterSpacing: 0.5 },
  headerGhostBtn: { borderRadius: radius.md, paddingVertical: spacing.sm + 2, paddingHorizontal: spacing.lg, borderWidth: 1.5, borderColor: colors.primary, backgroundColor: 'rgba(15, 76, 117, 0.05)' },
  headerGhostText: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold, color: colors.primary, letterSpacing: 0.3 },
  // Hero
  hero: { position: 'relative', minHeight: 620, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  heroBg: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, width: '100%', height: '100%' },
  heroOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(15, 76, 117, 0.25)' },
  heroContent: { zIndex: 2, alignItems: 'center', paddingHorizontal: spacing.xl, maxWidth: 720 },
  heroBadge: { backgroundColor: 'rgba(255, 255, 255, 0.25)', borderRadius: 20, paddingHorizontal: spacing.md + 4, paddingVertical: spacing.xs + 2, marginBottom: spacing.lg, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.4)' },
  heroBadgeText: { fontSize: fontSize.xs, fontWeight: fontWeight.semibold, color: colors.white, letterSpacing: 1 },
  heroTitle: { fontSize: 42, fontWeight: fontWeight.extrabold, color: colors.white, textAlign: 'center', lineHeight: 52, marginBottom: spacing.md },
  heroTitleAccent: { color: colors.accent },
  heroSubtitle: { fontSize: fontSize.lg, color: 'rgba(255, 255, 255, 0.85)', textAlign: 'center', lineHeight: fontSize.lg * 1.5, marginBottom: spacing.xl, maxWidth: 560 },
  heroBtnRow: { flexDirection: 'row', gap: spacing.md, flexWrap: 'wrap', justifyContent: 'center' },
  heroBtnPrimary: { backgroundColor: colors.accent, borderRadius: radius.md + 2, paddingVertical: spacing.md, paddingHorizontal: spacing.xl + 4, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, ...shadows.lg },
  heroBtnPrimaryText: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.primaryDark, letterSpacing: 0.5 },
  heroBtnSecondary: { borderRadius: radius.md + 2, paddingVertical: spacing.md, paddingHorizontal: spacing.xl + 4, borderWidth: 2, borderColor: 'rgba(255, 255, 255, 0.6)', flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: 'rgba(255, 255, 255, 0.1)' },
  heroBtnSecondaryText: { fontSize: fontSize.md, fontWeight: fontWeight.semibold, color: colors.white, letterSpacing: 0.3 },
  // Hero dots
  heroDots: { position: 'absolute', bottom: 24, left: 0, right: 0, flexDirection: 'row', justifyContent: 'center', gap: 8, zIndex: 3 },
  heroDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'rgba(255, 255, 255, 0.3)' },
  heroDotActive: { width: 24, borderRadius: 4, backgroundColor: colors.accent },
  // Section wrapper
  section: { paddingVertical: spacing.xxl + 16, paddingHorizontal: spacing.xl + 8 },
  sectionNarrow: { maxWidth: 1100, alignSelf: 'center', width: '100%' },
  sectionTitle: { fontSize: fontSize.xxl, fontWeight: fontWeight.extrabold, color: colors.primary, textAlign: 'center', marginBottom: spacing.xs },
  sectionTitleAccent: { color: colors.accentDark },
  sectionSubtitle: { fontSize: fontSize.md, color: colors.textSecondary, textAlign: 'center', marginBottom: spacing.xl, maxWidth: 560, alignSelf: 'center' },
  // About
  aboutBg: { backgroundColor: '#ffffff' },
  aboutGrid: { flexDirection: 'row', gap: spacing.lg, marginTop: spacing.lg, flexWrap: 'wrap', justifyContent: 'center' },
  aboutCard: { flex: 1, minWidth: 280, maxWidth: 340, backgroundColor: 'rgba(240, 244, 255, 0.8)', borderRadius: radius.lg, padding: spacing.xl, borderWidth: 1, borderColor: 'rgba(15, 76, 117, 0.08)', ...shadows.sm },
  aboutCardIconWrap: { width: 52, height: 52, borderRadius: 14, backgroundColor: 'rgba(255, 201, 60, 0.2)', justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  aboutCardIcon: { fontSize: 24 },
  aboutCardTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: colors.primary, marginBottom: spacing.xs },
  aboutCardText: { fontSize: fontSize.sm, color: colors.textSecondary, lineHeight: fontSize.sm * 1.6 },
  // Features
  featuresBg: { backgroundColor: '#f0f4ff' },
  featuresGrid: { flexDirection: 'row', gap: spacing.lg, marginTop: spacing.lg, flexWrap: 'wrap', justifyContent: 'center' },
  featureCard: { flex: 1, minWidth: 240, maxWidth: 300, backgroundColor: 'rgba(255, 255, 255, 0.9)', borderRadius: radius.lg, padding: spacing.xl, borderWidth: 1, borderColor: 'rgba(15, 76, 117, 0.06)', ...shadows.md },
  featureIconWrap: { width: 48, height: 48, borderRadius: 12, backgroundColor: 'rgba(15, 76, 117, 0.1)', justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md },
  featureIcon: { fontSize: 22 },
  featureTitle: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.primary, marginBottom: spacing.xs },
  featureText: { fontSize: fontSize.sm, color: colors.textSecondary, lineHeight: fontSize.sm * 1.5 },
  // Stats band
  statsBand: { backgroundColor: colors.primary, paddingVertical: spacing.xl + 8, paddingHorizontal: spacing.xl + 8 },
  statsBandGrid: { flexDirection: 'row', justifyContent: 'center', gap: spacing.xxl, flexWrap: 'wrap' },
  statsBandItem: { alignItems: 'center' },
  statsBandValue: { fontSize: 36, fontWeight: fontWeight.extrabold, color: colors.accent },
  statsBandLabel: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.7)', marginTop: 4, letterSpacing: 0.5 },
  // CTA section
  ctaSection: { paddingVertical: spacing.xxl + 20, paddingHorizontal: spacing.xl + 8, alignItems: 'center', backgroundColor: '#ffffff' },
  ctaTitle: { fontSize: fontSize.xxl, fontWeight: fontWeight.extrabold, color: colors.primary, textAlign: 'center', marginBottom: spacing.sm },
  ctaText: { fontSize: fontSize.md, color: colors.textSecondary, textAlign: 'center', marginBottom: spacing.xl, maxWidth: 480 },
  // Footer
  footer: { backgroundColor: colors.primaryDark, paddingVertical: spacing.xl + 8, paddingHorizontal: spacing.xl + 8 },
  footerGrid: { flexDirection: 'row', gap: spacing.xl, flexWrap: 'wrap', maxWidth: 1100, alignSelf: 'center' },
  footerCol: { flex: 1, minWidth: 200 },
  footerColWide: { flex: 1.5, minWidth: 280 },
  footerBrandRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm + 2, marginBottom: spacing.md },
  footerBrandBox: { width: 40, height: 40, borderRadius: 10, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center' },
  footerBrandText: { fontSize: fontSize.xs, fontWeight: fontWeight.extrabold, color: colors.primaryDark, letterSpacing: 1 },
  footerBrandName: { fontSize: fontSize.md, fontWeight: fontWeight.bold, color: colors.white },
  footerAbout: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', lineHeight: fontSize.sm * 1.6 },
  footerColTitle: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.accent, marginBottom: spacing.md, letterSpacing: 0.5 },
  footerLink: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)', marginBottom: spacing.sm + 2 },
  footerContactRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginBottom: spacing.sm + 2 },
  footerContactIcon: { fontSize: fontSize.sm, opacity: 0.7 },
  footerContactText: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.6)' },
  footerBottom: { borderTopWidth: 1, borderTopColor: 'rgba(255, 255, 255, 0.1)', marginTop: spacing.xl, paddingTop: spacing.lg, alignItems: 'center' },
  footerCopyright: { fontSize: fontSize.xs, color: 'rgba(255, 255, 255, 0.4)', letterSpacing: 0.3 },
  // Portal modal overlay
  portalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 200, backgroundColor: '#0a1628' },
  portalCloseBar: { position: 'absolute', top: 0, left: 0, right: 0, zIndex: 210, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.md, backgroundColor: 'rgba(10, 22, 40, 0.9)', borderBottomWidth: 1, borderBottomColor: 'rgba(255, 255, 255, 0.06)' },
  portalCloseLogo: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  portalCloseBtnRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, flexWrap: 'wrap' },
  portalCloseLogoBox: { width: 32, height: 32, borderRadius: 8, backgroundColor: colors.accent, justifyContent: 'center', alignItems: 'center' },
  portalCloseLogoText: { fontSize: 9, fontWeight: fontWeight.extrabold, color: colors.primaryDark },
  portalCloseSchool: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.white },
  portalCloseBtn: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingVertical: spacing.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: 'rgba(255, 255, 255, 0.06)' },
  portalCloseText: { fontSize: fontSize.sm, color: 'rgba(255, 255, 255, 0.7)', fontWeight: fontWeight.medium },
  portalBody: { flex: 1, marginTop: 56 },
});
