import type { RoleId } from '@shared/types';

export interface DashboardPageDef {
  key: string;
  label: string;
}

export interface DashboardDef {
  key: string;
  label: string;
  role: RoleId;
  pages: DashboardPageDef[];
}

export const DASHBOARD_CATALOG: DashboardDef[] = [
  {
    key: 'Headmaster',
    label: 'Headmaster',
    role: 'headmaster',
    pages: [
      { key: 'overview', label: 'Executive Overview' },
      { key: 'oversight', label: 'School-Wide Oversight' },
      { key: 'staff', label: 'Staff Directory & Appraisal' },
      { key: 'approvals', label: 'Approvals Inbox' },
      { key: 'reports', label: 'Reports & Analytics' },
      { key: 'communication', label: 'Communication' },
      { key: 'discipline', label: 'Discipline Case Log' },
      { key: 'users', label: 'User Management' },
      { key: 'access', label: 'Access Control' },
      { key: 'menu', label: "Today's Menu" },
      { key: 'sync', label: 'Sync & Data Health' },
    ],
  },
  {
    key: 'Academic',
    label: 'Asst. Headmaster (Academic)',
    role: 'asst_headmaster_academic',
    pages: [
      { key: 'overview', label: 'Academic Overview' },
      { key: 'monitor', label: 'Academic Monitor' },
      { key: 'insights', label: 'Insights & Analytics' },
      { key: 'timetable', label: 'Timetable Manager' },
      { key: 'exams', label: 'Exam Management' },
      { key: 'reports', label: 'Report Cards' },
      { key: 'transcripts', label: 'Transcripts' },
      { key: 'spip', label: 'School Improvement Plan' },
      { key: 'curriculum', label: 'Curriculum Tracker' },
      { key: 'calendar', label: 'Academic Calendar' },
      { key: 'hod', label: 'HOD Approvals' },
      { key: 'supplies', label: 'Stationery Requests' },
      { key: 'plc', label: 'PLC Requisitions' },
      { key: 'academic-reports', label: 'Reports & PDF' },
    ],
  },
  {
    key: 'Admin',
    label: 'Asst. Headmaster (Admin)',
    role: 'asst_headmaster_admin',
    pages: [
      { key: 'overview', label: 'Admin Overview' },
      { key: 'approvals', label: 'Approvals' },
      { key: 'compliance', label: 'Compliance Tracker' },
      { key: 'admissions', label: 'Admissions' },
      { key: 'cssps-upload', label: 'CSSPS Placement Upload' },
      { key: 'prospectus', label: 'Prospectus Publishing' },
      { key: 'admissions-config', label: 'Admission Form Config' },
      { key: 'scratch-cards', label: 'Scratch Cards' },
      { key: 'id-cards', label: 'Student ID Cards' },
      { key: 'staff', label: 'Staff Management' },
      { key: 'facilities', label: 'Facilities' },
      { key: 'meetings', label: 'Meetings' },
      { key: 'tasks', label: 'Task Assignments' },
      { key: 'communication', label: 'Communication' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Domestic',
    label: 'Asst. Headmaster (Domestic)',
    role: 'asst_headmaster_domestic',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'boarding', label: 'Boarding Houses' },
      { key: 'catering', label: 'Catering & Kitchen' },
      { key: 'transport', label: 'Transport' },
      { key: 'cleaning', label: 'Cleaning & Maintenance' },
      { key: 'approvals', label: 'Requisition Approvals' },
      { key: 'compliance', label: 'Compliance' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Bursary',
    label: 'Bursary',
    role: 'bursary',
    pages: [
      { key: 'overview', label: 'Bursary Overview' },
      { key: 'cashbook', label: 'Cash Book' },
      { key: 'studentAccounts', label: 'Student Accounts' },
      { key: 'pettyCash', label: 'Petty Cash' },
      { key: 'imprest', label: 'Imprest Accounts' },
      { key: 'procurement', label: 'Procurement' },
      { key: 'feeding', label: 'Feeding Account' },
      { key: 'boardingSupplies', label: 'Boarding Supplies' },
      { key: 'disbursements', label: 'Disbursements' },
      { key: 'returns', label: 'Daily/Monthly Returns' },
      { key: 'reports', label: 'Bursary Reports' },
    ],
  },
  {
    key: 'Accountant',
    label: 'Accountant',
    role: 'accountant',
    pages: [
      { key: 'overview', label: 'Financial Overview' },
      { key: 'fees', label: 'Fee / Capitation Ledger' },
      { key: 'invoices', label: 'Invoices' },
      { key: 'payroll', label: 'Payroll' },
      { key: 'expenditure', label: 'Expenditure Log' },
      { key: 'budgetSubmissions', label: 'Budget Submissions' },
      { key: 'budget', label: 'Budget Planner' },
      { key: 'kitchenFinance', label: 'Kitchen Finance' },
      { key: 'returnsApproval', label: 'Returns Approval' },
      { key: 'reports', label: 'Financial Reports' },
    ],
  },
  {
    key: 'Registry',
    label: 'Registry',
    role: 'registry',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'students', label: 'Student Records' },
      { key: 'admissions', label: 'Admissions' },
      { key: 'certificates', label: 'Certificates & Documents' },
      { key: 'correspondence', label: 'Correspondence Log' },
      { key: 'staff', label: 'Staff Records' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Stores',
    label: 'Stores',
    role: 'stores',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'inventory', label: 'Stock Inventory' },
      { key: 'received', label: 'Goods Received' },
      { key: 'requisition', label: 'Requisitions' },
      { key: 'kitchenIssues', label: 'Kitchen Issues' },
      { key: 'suppliers', label: 'Suppliers' },
      { key: 'audit', label: 'Stock Audit' },
      { key: 'alerts', label: 'Low-Stock Alerts' },
    ],
  },
  {
    key: 'Security',
    label: 'Security',
    role: 'security',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'gate', label: 'Gate Log' },
      { key: 'exeats', label: 'Exeat Verification' },
      { key: 'incidents', label: 'Incident Reports' },
      { key: 'patrol', label: 'Patrol Schedule' },
      { key: 'visitors', label: 'Visitor Pre-Reg' },
      { key: 'checklist', label: 'Daily Checklist' },
      { key: 'guards', label: 'Guards' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'House',
    label: 'Housemaster',
    role: 'housemaster',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'roster', label: 'House Roster' },
      { key: 'rooms', label: 'Room Allocation' },
      { key: 'rollcall', label: 'Roll Call' },
      { key: 'discipline', label: 'Discipline Log' },
      { key: 'welfare', label: 'Welfare Check' },
      { key: 'exeats', label: 'Exeats' },
      { key: 'requisitions', label: 'Requisitions' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'SeniorHousemaster',
    label: 'Senior Housemaster',
    role: 'senior_housemaster',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'assignments', label: 'House Assignments' },
      { key: 'approvals', label: 'Requisition Approvals' },
      { key: 'exeats', label: 'Exeat Approvals' },
      { key: 'houses', label: 'Houses' },
      { key: 'rollcall', label: 'Roll Call Summary' },
      { key: 'discipline', label: 'Discipline Log' },
      { key: 'welfare', label: 'Welfare Overview' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Catering',
    label: 'Catering / Kitchen',
    role: 'catering',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'menu', label: 'Menu Planner' },
      { key: 'customMenu', label: 'Special Diet Menus' },
      { key: 'stock', label: 'Kitchen Stock & Issuing' },
      { key: 'requisition', label: 'Food Stock Requisition' },
      { key: 'finance', label: 'Financial Request' },
      { key: 'headcount', label: 'Meal Headcount' },
      { key: 'staff', label: 'Kitchen Staff Roster' },
      { key: 'hygiene', label: 'Hygiene Inspection Log' },
      { key: 'cost', label: 'Food Cost Estimator' },
    ],
  },
  {
    key: 'Health',
    label: 'Health / Sick Bay',
    role: 'health',
    pages: [
      { key: 'patients', label: 'Patient Log' },
      { key: 'inventory', label: 'Medical Inventory' },
      { key: 'referrals', label: 'Referral Tracker' },
      { key: 'records', label: 'Health Records' },
      { key: 'reports', label: 'Health Reports' },
    ],
  },
  {
    key: 'Transport',
    label: 'Transport',
    role: 'transport',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'vehicles', label: 'Vehicle Registry' },
      { key: 'trips', label: 'Trip Log' },
      { key: 'maintenance', label: 'Maintenance' },
      { key: 'fuel', label: 'Fuel & Supplies' },
      { key: 'drivers', label: 'Driver Roster' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Cleaning',
    label: 'Cleaning / Labourers',
    role: 'cleaning',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'roster', label: 'Duty Roster' },
      { key: 'tasks', label: 'Task Checklist' },
      { key: 'supplies', label: 'Supply Inventory' },
      { key: 'requisitions', label: 'Supply Requests' },
      { key: 'staff', label: 'Staff Attendance' },
      { key: 'maintenance', label: 'Maintenance Issues' },
      { key: 'inspection', label: 'Inspection Reports' },
    ],
  },
  {
    key: 'Counselling',
    label: 'Counselling Unit',
    role: 'counselling',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'cases', label: 'Case Log' },
      { key: 'caseDetail', label: 'Case Details' },
      { key: 'appointments', label: 'Appointments' },
      { key: 'referrals', label: 'Referral Tracker' },
      { key: 'career', label: 'Career Resources' },
      { key: 'counsellors', label: 'Our Counsellors' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'LibraryICT',
    label: 'Library & ICT',
    role: 'library_ict',
    pages: [
      { key: 'catalogue', label: 'Catalogue' },
      { key: 'circulation', label: 'Borrow / Return' },
      { key: 'ict', label: 'ICT Lab Bookings' },
      { key: 'equipment', label: 'Equipment' },
      { key: 'digital', label: 'Digital Resources' },
      { key: 'access', label: 'Access Control' },
      { key: 'requisitions', label: 'Requisitions' },
    ],
  },
  {
    key: 'SportsClubs',
    label: 'Sports & Clubs',
    role: 'sports_clubs',
    pages: [
      { key: 'clubs', label: 'Clubs & Societies' },
      { key: 'fixtures', label: 'Sports Fixtures' },
      { key: 'participation', label: 'Participation' },
      { key: 'equipment', label: 'Equipment & Kits' },
      { key: 'achievements', label: 'Achievements' },
      { key: 'access', label: 'Access Control' },
      { key: 'requisitions', label: 'Requisitions' },
    ],
  },
  {
    key: 'PLC',
    label: 'PLC',
    role: 'plc',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'meetings', label: 'Meetings & Attendance' },
      { key: 'duty', label: 'Coordinator Duty Roster' },
      { key: 'observations', label: 'Critical Friend' },
      { key: 'lesson', label: 'Lesson Study Log' },
      { key: 'performance', label: 'Performance Review' },
      { key: 'resources', label: 'Resource Sharing' },
      { key: 'action', label: 'Action Plan Tracker' },
      { key: 'requisitions', label: 'PLC Requisitions' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'SubjectHOD',
    label: 'Subject HOD',
    role: 'subject_hod',
    pages: [
      { key: 'overview', label: 'Department Overview' },
      { key: 'syllabus', label: 'Syllabus Tracker' },
      { key: 'lesson', label: 'Lesson Plan Review' },
      { key: 'exam', label: 'Internal Exam Setting' },
      { key: 'results', label: 'Result Entry' },
    ],
  },
  {
    key: 'Teacher',
    label: 'Teacher',
    role: 'teacher',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'subjects', label: 'My Subjects & Classes' },
      { key: 'timetable', label: 'My Timetable' },
      { key: 'lessonPlans', label: 'Lesson Plans' },
      { key: 'materials', label: 'Lesson Materials' },
      { key: 'av', label: 'Audio & Video Library' },
      { key: 'live', label: 'Live / Virtual Class' },
      { key: 'assignments', label: 'Assignments & Assessments' },
      { key: 'gradebook', label: 'Gradebook' },
      { key: 'attendance', label: 'Class Attendance' },
      { key: 'roster', label: 'Student Roster' },
      { key: 'syllabus', label: 'Syllabus Tracker' },
      { key: 'remedial', label: 'Remedial Support' },
      { key: 'announcements', label: 'Class Announcements' },
      { key: 'plc', label: 'PLC' },
      { key: 'menu', label: "Today's Menu" },
    ],
  },
  {
    key: 'Staff',
    label: 'Staff',
    role: 'staff',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'notice', label: 'Staff Notice Board' },
      { key: 'minutes', label: 'Meeting Minutes' },
      { key: 'resources', label: 'Resource Library' },
      { key: 'leave', label: 'Leave Requests' },
      { key: 'directory', label: 'Staff Directory' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'Student',
    label: 'Student',
    role: 'student',
    pages: [
      { key: 'profile', label: 'Profile' },
      { key: 'timetable', label: 'Timetable' },
      { key: 'classes', label: 'My Classes' },
      { key: 'materials', label: 'Learning Materials' },
      { key: 'assignments', label: 'Assignments' },
      { key: 'results', label: 'Results & Report Cards' },
      { key: 'attendance', label: 'Attendance' },
      { key: 'fees', label: 'Fees / Capitation' },
      { key: 'library', label: 'Library Account' },
      { key: 'health', label: 'Health Record' },
      { key: 'elections', label: 'Elections' },
      { key: 'feedback', label: 'Grievance / Feedback' },
    ],
  },
  {
    key: 'Parent',
    label: 'Parent',
    role: 'parent',
    pages: [
      { key: 'wards', label: 'My Children' },
      { key: 'academic', label: 'Academic Reports' },
      { key: 'attendance', label: 'Attendance' },
      { key: 'exeats', label: 'Exeats' },
      { key: 'discipline', label: 'Discipline & Welfare' },
      { key: 'health', label: 'Health Records' },
      { key: 'announcements', label: 'Announcements' },
      { key: 'meetings', label: 'Meetings & RSVP' },
      { key: 'payments', label: 'Payments' },
      { key: 'fundraising', label: 'Fundraising' },
      { key: 'feedback', label: 'Feedback' },
      { key: 'directory', label: 'Parent Directory' },
    ],
  },
  {
    key: 'SRC',
    label: 'SRC',
    role: 'src',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'announcements', label: 'Announcements' },
      { key: 'events', label: 'Event Planner' },
      { key: 'grievances', label: 'Grievance Log' },
      { key: 'prefects', label: 'Prefect Roster' },
      { key: 'budget', label: 'Budget Tracker' },
      { key: 'initiatives', label: 'Initiatives' },
      { key: 'feedback', label: 'Student Feedback' },
    ],
  },
  {
    key: 'ElectoralCommission',
    label: 'Electoral Commission',
    role: 'electoral_commission',
    pages: [
      { key: 'calendar', label: 'Election Calendar' },
      { key: 'candidates', label: 'Candidate Registration' },
      { key: 'voters', label: 'Voter Roll' },
      { key: 'ballot', label: 'Ballot Management' },
      { key: 'voting', label: 'Voting & Live Results' },
      { key: 'reports', label: 'Election Reports' },
      { key: 'settings', label: 'Settings' },
    ],
  },
  {
    key: 'PTA',
    label: 'PTA',
    role: 'pta',
    pages: [
      { key: 'wards', label: 'My Ward(s)' },
      { key: 'announcements', label: 'Announcements' },
      { key: 'fundraising', label: 'Fundraising' },
      { key: 'meetings', label: 'Meetings' },
      { key: 'directory', label: 'Directory' },
      { key: 'dues', label: 'PTA Dues' },
      { key: 'finance', label: 'Finance' },
      { key: 'feedback', label: 'Feedback' },
      { key: 'access', label: 'Access Control' },
    ],
  },
  {
    key: 'GoverningBoard',
    label: 'Governing Board',
    role: 'governing_board',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'policy', label: 'Policy Documents' },
      { key: 'budget', label: 'Budget Approvals' },
      { key: 'minutes', label: 'Meeting Minutes' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'WelfareCommittee',
    label: 'Welfare Committee',
    role: 'welfare_committee',
    pages: [
      { key: 'ledger', label: 'Welfare Fund Ledger' },
      { key: 'support', label: 'Support Requests' },
      { key: 'disbursement', label: 'Disbursement Approvals' },
      { key: 'membership', label: 'Membership Register' },
    ],
  },
  {
    key: 'SystemAdmin',
    label: 'System Administrator',
    role: 'system_admin',
    pages: [
      { key: 'overview', label: 'System Overview' },
      { key: 'users', label: 'User Management' },
      { key: 'tenant', label: 'School Configuration' },
      { key: 'modules', label: 'Modules' },
      { key: 'database', label: 'Database & Sync' },
      { key: 'backups', label: 'Backups' },
      { key: 'logs', label: 'System Logs' },
    ],
  },
  {
    key: 'Chaplain',
    label: 'Chaplain',
    role: 'chaplain',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'services', label: 'Service Schedule' },
      { key: 'prayerRequests', label: 'Prayer Requests' },
      { key: 'counselling', label: 'Spiritual Counselling' },
      { key: 'events', label: 'Religious Events' },
      { key: 'fellowships', label: 'Fellowship Groups' },
      { key: 'outreach', label: 'Outreach & Charity' },
      { key: 'choir', label: 'Choir & Music' },
      { key: 'baptism', label: 'Baptism & Dedication' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'AcademicBoard',
    label: 'Academic Board',
    role: 'academic_board',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'planning', label: 'Academic Planning' },
      { key: 'curriculum', label: 'Curriculum Oversight' },
      { key: 'policy', label: 'Academic Policies' },
      { key: 'departments', label: 'Department Reports' },
      { key: 'assessments', label: 'Assessment Review' },
      { key: 'calendar', label: 'Academic Calendar' },
      { key: 'meetings', label: 'Board Meetings' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'DiningHall',
    label: 'Dining Hall Master',
    role: 'dining_hall_master',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'seating', label: 'Seating Plan' },
      { key: 'menu', label: 'Menu Oversight' },
      { key: 'attendance', label: 'Meal Attendance' },
      { key: 'supplies', label: 'Supplies & Stock' },
      { key: 'hygiene', label: 'Hygiene Inspection' },
      { key: 'feedback', label: 'Student Feedback' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'ExamCommittee',
    label: 'Examination Committee',
    role: 'exam_committee',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'schedule', label: 'Exam Schedule' },
      { key: 'papers', label: 'Question Papers' },
      { key: 'invigilation', label: 'Invigilation Duty' },
      { key: 'grading', label: 'Grading & Moderation' },
      { key: 'results', label: 'Results Processing' },
      { key: 'malpractice', label: 'Malpractice Log' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'SafeSpace',
    label: 'Safe Space',
    role: 'safe_space',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'incidents', label: 'Safety Incidents' },
      { key: 'inspections', label: 'Safety Inspections' },
      { key: 'relationships', label: 'Relationship Management' },
      { key: 'environment', label: 'Environment Audit' },
      { key: 'training', label: 'Safety Training' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'InternalAuditor',
    label: 'Internal Auditor',
    role: 'internal_auditor',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'audits', label: 'Audit Schedule' },
      { key: 'findings', label: 'Audit Findings' },
      { key: 'compliance', label: 'Compliance Review' },
      { key: 'financial', label: 'Financial Audit' },
      { key: 'reports', label: 'Reports' },
    ],
  },
  {
    key: 'HeadmasterSecretary',
    label: 'Headmaster Secretary',
    role: 'headmaster_secretary',
    pages: [
      { key: 'overview', label: 'Overview' },
      { key: 'appointments', label: 'Appointments' },
      { key: 'correspondence', label: 'Correspondence' },
      { key: 'filing', label: 'Filing & Records' },
      { key: 'visitors', label: 'Visitor Log' },
      { key: 'tasks', label: 'Task Tracker' },
      { key: 'reports', label: 'Reports' },
    ],
  },
];

export const DASHBOARD_MAP: Record<string, DashboardDef> = DASHBOARD_CATALOG.reduce(
  (acc, d) => { acc[d.key] = d; return acc; },
  {} as Record<string, DashboardDef>
);
