import { RoleId } from '@shared/types';

/** Maps each role to its dashboard route name */
export const ROLE_DASHBOARD_MAP: Record<RoleId, string> = {
  governing_board: 'GoverningBoard',
  pta: 'PTA',
  headmaster: 'Headmaster',
  staff: 'Staff',
  welfare_committee: 'WelfareCommittee',
  src: 'SRC',
  electoral_commission: 'ElectoralCommission',
  asst_headmaster_academic: 'Academic',
  subject_hod: 'SubjectHOD',
  counselling: 'Counselling',
  library_ict: 'LibraryICT',
  sports_clubs: 'SportsClubs',
  plc: 'PLC',
  teacher: 'Teacher',
  asst_headmaster_admin: 'Admin',
  bursary: 'Bursary',
  accountant: 'Accountant',
  stores: 'Stores',
  registry: 'Registry',
  security: 'Security',
  asst_headmaster_domestic: 'Domestic',
  senior_housemaster: 'SeniorHousemaster',
  senior_housemistress: 'SeniorHousemaster',
  housemaster: 'House',
  housemistress: 'House',
  catering: 'Catering',
  health: 'Health',
  transport: 'Transport',
  cleaning: 'Cleaning',
  student: 'Student',
  parent: 'Parent',
  chaplain: 'Chaplain',
  academic_board: 'AcademicBoard',
  dining_hall_master: 'DiningHall',
  exam_committee: 'ExamCommittee',
  safe_space: 'SafeSpace',
  internal_auditor: 'InternalAuditor',
  headmaster_secretary: 'HeadmasterSecretary',
  system_admin: 'SystemAdmin',
};

/** Human-readable role labels */
export const ROLE_LABELS: Record<RoleId, string> = {
  governing_board: 'Governing Board',
  pta: 'PTA',
  headmaster: 'Headmaster',
  staff: 'Staff',
  welfare_committee: 'Welfare Committee',
  src: 'SRC',
  electoral_commission: 'Electoral Commission',
  asst_headmaster_academic: 'Asst. Headmaster (Academic)',
  subject_hod: 'Subject HOD',
  counselling: 'Counselling Unit',
  library_ict: 'Library & ICT',
  sports_clubs: 'Sports & Clubs',
  plc: 'PLC',
  teacher: 'Teacher',
  asst_headmaster_admin: 'Asst. Headmaster (Admin)',
  bursary: 'Bursary',
  accountant: 'Accountant',
  stores: 'Stores',
  registry: 'Registry',
  security: 'Security',
  asst_headmaster_domestic: 'Asst. Headmaster (Domestic)',
  senior_housemaster: 'Senior Housemaster',
  senior_housemistress: 'Senior Housemistress',
  housemaster: 'Housemaster',
  housemistress: 'Housemistress',
  catering: 'Catering / Kitchen',
  health: 'Health / Sick Bay',
  transport: 'Transport',
  cleaning: 'Cleaning / Labourers',
  student: 'Student',
  parent: 'Parent',
  chaplain: 'Chaplain',
  academic_board: 'Academic Board',
  dining_hall_master: 'Dining Hall Master',
  exam_committee: 'Examination Committee',
  safe_space: 'Safe Space',
  internal_auditor: 'Internal Auditor',
  headmaster_secretary: 'Headmaster Secretary',
  system_admin: 'System Administrator',
};
