import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    // ── Registry ──────────────────────────────────────────────
    tableSchema({
      name: 'students',
      columns: [
        { name: 'admission_number', type: 'string' },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'date_of_birth', type: 'string' },
        { name: 'gender', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'house_id', type: 'string', isOptional: true },
        { name: 'guardian_name', type: 'string' },
        { name: 'guardian_phone', type: 'string' },
        { name: 'guardian_address', type: 'string' },
        { name: 'admission_date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'placements',
      columns: [
        { name: 'full_name', type: 'string' },
        { name: 'cssps_placement_ref', type: 'string', isOptional: true },
        { name: 'intended_class_section_id', type: 'string', isOptional: true },
        { name: 'preloaded_by_staff_id', type: 'string' },
        { name: 'matched', type: 'boolean' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'admission_applications',
      columns: [
        { name: 'placement_record_id', type: 'string' },
        { name: 'applicant_name', type: 'string' },
        { name: 'parent_name', type: 'string' },
        { name: 'parent_phone', type: 'string' },
        { name: 'parent_email', type: 'string', isOptional: true },
        { name: 'documents_verified', type: 'boolean' },
        { name: 'processed_by_staff_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'resulting_student_record_id', type: 'string', isOptional: true },
        { name: 'resulting_parent_account_id', type: 'string', isOptional: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'parent_accounts',
      columns: [
        { name: 'full_name', type: 'string' },
        { name: 'phone', type: 'string' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'ward_student_ids', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'certificates',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'issued_by_staff_id', type: 'string' },
        { name: 'issued_at', type: 'string' },
        { name: 'file_local_path', type: 'string', isOptional: true },
        { name: 'file_remote_url', type: 'string', isOptional: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'correspondence_logs',
      columns: [
        { name: 'direction', type: 'string' },
        { name: 'subject', type: 'string' },
        { name: 'counterparty', type: 'string' },
        { name: 'logged_by_staff_id', type: 'string' },
        { name: 'logged_at', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'staff',
      columns: [
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string' },
        { name: 'position', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'date_of_employment', type: 'string' },
        { name: 'qualifications', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),

    // ── Teaching ──────────────────────────────────────────────
    tableSchema({
      name: 'subjects',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'code', type: 'string' },
        { name: 'department_id', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'class_sections',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'level', type: 'string' },
        { name: 'programme', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'teacher_assignments',
      columns: [
        { name: 'teacher_id', type: 'string' },
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'assigned_by_hod_id', type: 'string' },
        { name: 'active', type: 'boolean' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'enrollments',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'lesson_materials',
      columns: [
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'teacher_id', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'topic', type: 'string' },
        { name: 'local_file_path', type: 'string', isOptional: true },
        { name: 'remote_file_url', type: 'string', isOptional: true },
        { name: 'duration_seconds', type: 'number', isOptional: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'live_class_sessions',
      columns: [
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'teacher_id', type: 'string' },
        { name: 'scheduled_at', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'recording_material_id', type: 'string', isOptional: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'assignments',
      columns: [
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'teacher_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'instructions', type: 'string' },
        { name: 'due_at', type: 'string' },
        { name: 'attachment_material_ids', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'submissions',
      columns: [
        { name: 'assignment_id', type: 'string' },
        { name: 'student_id', type: 'string' },
        { name: 'text_response', type: 'string', isOptional: true },
        { name: 'attachment_local_paths', type: 'string' },
        { name: 'attachment_remote_urls', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'score', type: 'number', isOptional: true },
        { name: 'max_score', type: 'number', isOptional: true },
        { name: 'feedback', type: 'string', isOptional: true },
        { name: 'graded_by_teacher_id', type: 'string', isOptional: true },
        { name: 'graded_at', type: 'string', isOptional: true },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'assessments',
      columns: [
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'student_id', type: 'string' },
        { name: 'teacher_id', type: 'string' },
        { name: 'term', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'score', type: 'number' },
        { name: 'max_score', type: 'number' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'class_attendance',
      columns: [
        { name: 'subject_id', type: 'string' },
        { name: 'class_section_id', type: 'string' },
        { name: 'student_id', type: 'string' },
        { name: 'date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'recorded_by_teacher_id', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),

    // ── Bursary ───────────────────────────────────────────────
    tableSchema({
      name: 'student_fee_ledgers',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'term', type: 'string' },
        { name: 'academic_year', type: 'string' },
        { name: 'total_due', type: 'number' },
        { name: 'amount_paid', type: 'number' },
        { name: 'balance', type: 'number' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'fee_payments',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'ledger_id', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'method', type: 'string' },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'recorded_by_staff_id', type: 'string' },
        { name: 'paid_at', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'payroll_records',
      columns: [
        { name: 'staff_id', type: 'string' },
        { name: 'month', type: 'string' },
        { name: 'gross_pay', type: 'number' },
        { name: 'deductions', type: 'number' },
        { name: 'net_pay', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'expenditure_entries',
      columns: [
        { name: 'category', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'linked_requisition_id', type: 'string', isOptional: true },
        { name: 'approved_by_staff_id', type: 'string' },
        { name: 'spent_at', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'budget_lines',
      columns: [
        { name: 'term', type: 'string' },
        { name: 'academic_year', type: 'string' },
        { name: 'department', type: 'string' },
        { name: 'allocated_amount', type: 'number' },
        { name: 'spent_amount', type: 'number' },
        { name: 'approval_status', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),

    // ── Boarding ──────────────────────────────────────────────
    tableSchema({
      name: 'houses',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'gender', type: 'string' },
        { name: 'capacity', type: 'number' },
        { name: 'housemaster_staff_id', type: 'string' },
        { name: 'senior_supervisor_staff_id', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'room_allocations',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'house_id', type: 'string' },
        { name: 'room_number', type: 'string' },
        { name: 'bed_number', type: 'string' },
        { name: 'term', type: 'string' },
        { name: 'academic_year', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'roll_call_entries',
      columns: [
        { name: 'house_id', type: 'string' },
        { name: 'student_id', type: 'string' },
        { name: 'date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'recorded_by_staff_id', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'house_discipline_logs',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'house_id', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'action_taken', type: 'string', isOptional: true },
        { name: 'recorded_by_staff_id', type: 'string' },
        { name: 'occurred_at', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'welfare_check_logs',
      columns: [
        { name: 'student_id', type: 'string' },
        { name: 'house_id', type: 'string' },
        { name: 'note', type: 'string' },
        { name: 'recorded_by_staff_id', type: 'string' },
        { name: 'checked_at', type: 'string' },
        { name: 'tenant_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),

    // ── Sync queue ────────────────────────────────────────────
    tableSchema({
      name: 'sync_queue',
      columns: [
        { name: 'entity_id', type: 'string' },
        { name: 'entity_type', type: 'string' },
        { name: 'operation', type: 'string' },
        { name: 'payload', type: 'string' },
        { name: 'timestamp', type: 'number' },
        { name: 'device_id', type: 'string' },
        { name: 'attempts', type: 'number' },
        { name: 'last_error', type: 'string', isOptional: true },
      ],
    }),
  ],
});
